export { AAIGateway, createGateway } from './mcp/server.js';
export { AutomationError, ErrorCode, Errors } from './errors/errors.js';
export { logger } from './utils/logger.js';
export { loadConfig } from './config/config-loader.js';
export type { GatewayConfig } from './config/config-loader.js';
export { AppRegistry, scanAllPaths } from './config/discovery.js';
export type { DiscoveredApp } from './config/discovery.js';
export { validateAaiJson, isValidAaiJson } from './parsers/schema.js';
export type { AaiJson } from './parsers/schema.js';
export { getCurrentPlatform, replaceParams, parseJsonOutput } from './executors/base.js';
export type { AutomationExecutor, ExecutionResult, ExecutorOptions } from './executors/base.js';
export { MacOSExecutor, createMacOSExecutor } from './executors/macos.js';
export { WindowsExecutor, createWindowsExecutor } from './executors/windows.js';
export { LinuxExecutor, createLinuxExecutor } from './executors/linux.js';
export type { DBusConfig } from './executors/linux.js';
export { WebServer, startWebServer } from './web/server.js';
export type { CallHistoryEntry } from './web/server.js';
